# Generated by Django 6.0.2 on 2026-02-17 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('project_title', models.CharField(max_length=500)),
                ('project_description', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount of funding requested', max_digits=15)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('match_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Proposed matching contribution amount', max_digits=15, null=True)),
                ('match_description', models.TextField(blank=True, default='', help_text='Description of matching funds or in-kind contributions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='If True, this comment is visible only to staff reviewers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Comment',
                'verbose_name_plural': 'Application Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='applications/docs/')),
                ('document_type', models.CharField(choices=[('narrative', 'Project Narrative'), ('budget', 'Budget'), ('budget_justification', 'Budget Justification'), ('letters_of_support', 'Letters of Support'), ('resumes', 'Resumes / CVs'), ('organizational_chart', 'Organizational Chart'), ('audit_report', 'Audit Report'), ('tax_exempt_letter', 'Tax-Exempt Determination Letter'), ('other', 'Other')], default='other', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=255)),
                ('section_order', models.IntegerField(default=0)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Flexible form data stored as JSON')),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Application Section',
                'verbose_name_plural': 'Application Sections',
                'ordering': ['section_order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Status History',
                'verbose_name_plural': 'Application Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
