# Generated by Django 6.0.2 on 2026-02-17 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='applications/staff_docs/')),
                ('document_type', models.CharField(choices=[('verification', 'Verification Document'), ('background_check', 'Background Check'), ('due_diligence', 'Due Diligence Memo'), ('reference_check', 'Reference Check'), ('site_visit', 'Site Visit Report'), ('legal_review', 'Legal Review'), ('financial_review', 'Financial Review'), ('other', 'Other')], default='other', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_staff_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComplianceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('sam_registration', 'SAM Registration Active'), ('tax_exempt', 'Tax-Exempt Status Verified'), ('audit_clearance', 'Audit Clearance'), ('debarment_check', 'Debarment / Suspension Check'), ('budget_review', 'Budget Review Complete'), ('narrative_review', 'Narrative Review Complete'), ('insurance_verified', 'Insurance Verification'), ('match_verified', 'Match Funds Verified'), ('conflict_of_interest', 'Conflict of Interest Check'), ('eligibility_confirmed', 'Eligibility Confirmed')], max_length=30)),
                ('label', models.CharField(help_text='Human-readable description of the compliance requirement', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Staff notes about this compliance item')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this item must be verified before approval')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_compliance_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Compliance Item',
                'verbose_name_plural': 'Application Compliance Items',
                'ordering': ['item_type'],
                'unique_together': {('application', 'item_type')},
            },
        ),
    ]
