# Generated by Django 6.0.2 on 2026-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_staffdocument_applicationcomplianceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='version_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
