# Generated by Django 6.0.2 on 2026-02-21 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_version_application_version_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('claimed', 'Self-Claimed'), ('manager_assigned', 'Manager Assigned')], default='claimed', max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reassigned', 'Reassigned')], default='assigned', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='applications.application')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The manager who made this assignment (null if self-claimed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Assignment',
                'verbose_name_plural': 'Application Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
