# Generated by Django 6.0.2 on 2026-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
