# Generated by Django 6.0.2 on 2026-02-18 19:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('application', 'Application'), ('award', 'Award'), ('drawdown', 'Drawdown Request'), ('report', 'Report'), ('audit_log', 'Audit Log'), ('transaction', 'Transaction')], max_length=20)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_description', models.TextField(blank=True)),
                ('retention_policy', models.CharField(choices=[('standard', 'Standard (7 years)'), ('extended', 'Extended (10 years)'), ('permanent', 'Permanent'), ('federal', 'Federal Requirement (3 years post-closeout)')], default='standard', max_length=15)),
                ('original_created_at', models.DateTimeField(help_text='When the original record was created')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, help_text='When this archived record can be permanently deleted', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Preserved metadata from the archived record')),
                ('is_purged', models.BooleanField(default=False, help_text='Whether the original record has been purged from the system')),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archived Record',
                'verbose_name_plural': 'Archived Records',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='idx_archive_entity'), models.Index(fields=['retention_expires_at'], name='idx_archive_expiry')],
            },
        ),
    ]
