# Generated by Django 6.0.2 on 2026-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_archivedrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('agency_admin', 'Agency Administrator'), ('program_officer', 'Program Officer'), ('fiscal_officer', 'Fiscal Officer'), ('federal_coordinator', 'Federal Fund Coordinator'), ('reviewer', 'Reviewer'), ('applicant', 'Applicant'), ('auditor', 'Auditor')], default='applicant', max_length=25),
        ),
    ]
