# Generated by Django 6.0.2 on 2026-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anthropic_api_key',
            field=models.CharField(blank=True, default='', help_text='Personal Claude API key for AI-powered grant matching.', max_length=255, verbose_name='Anthropic API Key'),
        ),
    ]
