# Generated by Django 6.0.2 on 2026-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_anthropic_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='department_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='State ERP Department Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_state_user',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a state government employee.'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_recip_read'),
        ),
    ]
