"""Concrete Activity + Watcher models for Harbor.

Fifth product wiring of keel.activity (Phase 1A Week 5 / Phase 1C — second
non-Phase-1A peer, after Lookout). Models live in the ``applications`` app
since Application is the user-facing record activity rotates around — see
keel/CLAUDE.md "Project Lifecycle Standard" which calls out Harbor's
Application as the reference implementation for the full lifecycle.

Harbor doesn't have a per-record collaborator model (unlike Beacon contacts /
Helm projects / Lookout tracked bills): applications are scoped by the
applicant (the org-side submitter), the organization the applicant belongs
to, the staff_assignments (`ApplicationAssignment`) for processing, and the
review_assignments (`ReviewAssignment`) for scoring. ``visible_to`` honors
all four channels.

Watcher subscribes a user to an Application — same shape as the other peers.
There's no pre-existing Harbor "follow" primitive to migrate from.
"""
from __future__ import annotations

from django.db import models
from django.db.models import Q

from keel.activity.models import AbstractActivity, AbstractWatcher

from .models import Application, ApplicationAssignment


class Activity(AbstractActivity):
    """Per-product Activity row for Harbor applications.

    Inherits the abstract base + adds a denormalized ``application`` FK so
    an Application detail page reads its activity feed via a single index seek
    rather than a GFK round-trip. Backfilled from the target GFK in ``save()``
    when target IS an Application (the common case for Track A promotions).
    """

    application = models.ForeignKey(
        Application,
        on_delete=models.CASCADE,
        related_name='activities',
        db_index=True,
        null=True, blank=True,
        help_text='Denormalized FK to Application for fast detail-page queries. '
                  'Backfilled from target on save when target IS an Application.',
    )

    class Meta(AbstractActivity.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=['audit_ref'],
                condition=models.Q(audit_ref__isnull=False),
                name='applic_activity_aud_uniq',
            ),
        ]
        indexes = [
            models.Index(
                fields=['target_ct', 'target_id', '-created_at'],
                name='applic_activity_tgt_ix',
            ),
            models.Index(
                fields=['actor', '-created_at'],
                name='applic_activity_act_ix',
            ),
            models.Index(
                fields=['verb', '-created_at'],
                name='applic_activity_verb_ix',
            ),
            models.Index(
                fields=['application', '-created_at'],
                name='applic_activity_app_ix',
            ),
        ]

    def save(self, *args, **kwargs):
        # Backfill the denormalized application FK from target when target IS an Application.
        if self.application_id is None and self.target_id and self.target_ct_id:
            try:
                if self.target_ct.model == 'application':
                    # target_id is CharField(max_length=64) on AbstractActivity to fit UUIDs.
                    # Application.id IS a UUID, so assign directly.
                    self.application_id = self.target_id
            except Exception:
                pass
        super().save(*args, **kwargs)

    @classmethod
    def visible_to(cls, user, queryset=None):
        """Visibility on Harbor applications.

        An activity is visible to a user when ANY of:
          1. user is the applicant on the Application
          2. user has an ApplicationAssignment (active or historical — staff
             see their own past work)
          3. user has a ReviewAssignment (reviewer access)
          4. user is in the same organization as the application's
             ``organization`` FK (org-level peers)

        Staff/superuser bypass. Stub-tier rows are not generated by Harbor's
        promotion rules in v1; the abstract base supports them and this
        method treats them like collaborator-tier (visible to anyone who can
        see the underlying application).
        """
        qs = queryset if queryset is not None else cls.objects.all()
        if user is None:
            return qs.none()
        if getattr(user, 'is_superuser', False):
            return qs

        # Applications the user has access to via the four channels.
        owned_ids = set(
            Application.objects.filter(applicant=user).values_list('id', flat=True)
        )
        owned_ids.update(
            ApplicationAssignment.objects.filter(assigned_to=user)
            .values_list('application_id', flat=True)
        )
        # Reviewer access — keep import local to avoid circular import at
        # module load (applications imports reviews indirectly via FK strings).
        try:
            from reviews.models import ReviewAssignment  # noqa: WPS433
            owned_ids.update(
                ReviewAssignment.objects.filter(reviewer=user)
                .values_list('application_id', flat=True)
            )
        except Exception:
            pass
        # Org-level peers — same harbor_core.Organization as the application.
        # HarborProfile.organization (OneToOne via user.harbor_profile) is the
        # canonical link; bail if the user has no profile or no org.
        try:
            org_id = user.harbor_profile.organization_id
        except Exception:
            org_id = None
        if org_id:
            owned_ids.update(
                Application.objects.filter(organization_id=org_id)
                .values_list('id', flat=True)
            )

        if not owned_ids:
            return qs.none()

        return qs.filter(
            Q(application_id__in=owned_ids),
            ~Q(visibility='staff'),
        )

    @classmethod
    def is_visible_to_user(cls, user, activity) -> bool:
        if user is None:
            return False
        if getattr(user, 'is_superuser', False):
            return True
        if activity.visibility == 'staff':
            return False
        if activity.application_id is None:
            return False
        if Application.objects.filter(id=activity.application_id, applicant=user).exists():
            return True
        if ApplicationAssignment.objects.filter(
            application_id=activity.application_id, assigned_to=user,
        ).exists():
            return True
        try:
            from reviews.models import ReviewAssignment  # noqa: WPS433
            if ReviewAssignment.objects.filter(
                application_id=activity.application_id, reviewer=user,
            ).exists():
                return True
        except Exception:
            pass
        try:
            org_id = user.harbor_profile.organization_id
        except Exception:
            org_id = None
        if org_id and Application.objects.filter(
            id=activity.application_id, organization_id=org_id,
        ).exists():
            return True
        return False


class Watcher(AbstractWatcher):
    """Per-product Watcher for Harbor. Same shape as the other peers."""
    class Meta(AbstractWatcher.Meta):
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'target_ct', 'target_id'],
                condition=models.Q(target_ct__isnull=False) & models.Q(target_id__isnull=False),
                name='applic_watcher_uniq',
            ),
        ]
        indexes = [
            models.Index(
                fields=['user', 'target_ct', 'target_id'],
                name='applic_watcher_ut_ix',
            ),
        ]
