# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='awards.award')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['award', '-fiscal_year'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('personnel', 'Personnel'), ('fringe', 'Fringe Benefits'), ('travel', 'Travel'), ('equipment', 'Equipment'), ('supplies', 'Supplies'), ('contractual', 'Contractual'), ('construction', 'Construction'), ('indirect', 'Indirect Costs'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('federal_share', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('state_share', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('match_share', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='financial.budget')),
            ],
            options={
                'verbose_name': 'Budget Line Item',
                'verbose_name_plural': 'Budget Line Items',
            },
        ),
        migrations.CreateModel(
            name='CoreCTAccountString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fund', models.CharField(max_length=5, verbose_name='Fund')),
                ('department', models.CharField(max_length=8, verbose_name='Department')),
                ('sid', models.CharField(max_length=5, verbose_name='SID')),
                ('program', models.CharField(max_length=5, verbose_name='Program')),
                ('account', models.CharField(max_length=5, verbose_name='Account')),
                ('chartfield1', models.CharField(blank=True, max_length=6, verbose_name='Chartfield 1')),
                ('chartfield2', models.CharField(blank=True, max_length=8, verbose_name='Chartfield 2')),
                ('budget_ref_year', models.CharField(blank=True, max_length=4, verbose_name='Budget Ref Year')),
                ('project', models.CharField(blank=True, max_length=15, verbose_name='Project')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_strings', to='awards.award')),
            ],
            options={
                'verbose_name': 'Core-CT Account String',
                'verbose_name_plural': 'Core-CT Account Strings',
            },
        ),
        migrations.CreateModel(
            name='DrawdownRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('denied', 'Denied'), ('returned', 'Returned')], default='draft', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('expenditure_details', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_requests', to='awards.award')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drawdowns', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_drawdowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drawdown Request',
                'verbose_name_plural': 'Drawdown Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('obligation', 'Obligation'), ('drawdown', 'Drawdown'), ('payment', 'Payment'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('core_ct_reference', models.CharField(blank=True, help_text='Reference ID from the Core-CT financial system.', max_length=100, verbose_name='Core-CT Reference')),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='awards.award')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
