# Generated by Django 6.0.2 on 2026-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corectaccountstring',
            options={'verbose_name': 'State ERP Account String', 'verbose_name_plural': 'State ERP Account Strings'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='core_ct_reference',
            field=models.CharField(blank=True, help_text='Reference ID from the state enterprise financial system.', max_length=100, verbose_name='State ERP Reference'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
    ]
