# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State'), ('private', 'Private'), ('mixed', 'Mixed')], default='state', max_length=20)),
                ('cfda_number', models.CharField(blank=True, default='', help_text='Catalog of Federal Domestic Assistance number (federal sources only)', max_length=20)),
                ('federal_agency', models.CharField(blank=True, default='', help_text='Originating federal agency, if applicable', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funding Source',
                'verbose_name_plural': 'Funding Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrantProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('grant_type', models.CharField(choices=[('competitive', 'Competitive'), ('non_competitive', 'Non-Competitive'), ('formula', 'Formula'), ('continuation', 'Continuation'), ('other', 'Other')], default='competitive', max_length=20)),
                ('eligibility_criteria', models.TextField(blank=True, default='', help_text='Description of who may apply')),
                ('total_funding', models.DecimalField(decimal_places=2, help_text='Total funding available for this program', max_digits=15)),
                ('min_award', models.DecimalField(decimal_places=2, help_text='Minimum award amount', max_digits=15)),
                ('max_award', models.DecimalField(decimal_places=2, help_text='Maximum award amount', max_digits=15)),
                ('match_required', models.BooleanField(default=False, help_text='Whether a matching contribution is required')),
                ('match_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Required match as a percentage (e.g. 25.00 for 25%)', max_digits=5, null=True)),
                ('fiscal_year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('multi_year', models.BooleanField(default=False, help_text='Whether awards span multiple fiscal years')),
                ('duration_months', models.IntegerField(help_text='Grant period duration in months')),
                ('application_deadline', models.DateTimeField()),
                ('posting_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('accepting_applications', 'Accepting Applications'), ('under_review', 'Under Review'), ('awards_pending', 'Awards Pending'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_programs', to='core.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_grant_programs', to=settings.AUTH_USER_MODEL)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_programs', to='grants.fundingsource')),
            ],
            options={
                'verbose_name': 'Grant Program',
                'verbose_name_plural': 'Grant Programs',
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='GrantProgramDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='grant_programs/docs/')),
                ('document_type', models.CharField(choices=[('nofa', 'Notice of Funding Availability'), ('guidelines', 'Program Guidelines'), ('budget_template', 'Budget Template'), ('application_form', 'Application Form'), ('faq', 'FAQ'), ('amendment', 'Amendment'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='grants.grantprogram')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_grant_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Program Document',
                'verbose_name_plural': 'Grant Program Documents',
                'ordering': ['document_type', 'title'],
            },
        ),
    ]
