# Generated by Django 6.0.2 on 2026-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantprogram',
            name='application_form_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration defining custom application form sections and fields per program'),
        ),
    ]
