# Generated by Django 6.0.2 on 2026-02-21 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_grantprogram_application_form_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalOpportunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_id', models.IntegerField(help_text='Unique identifier from Grants.gov', unique=True)),
                ('opportunity_number', models.CharField(blank=True, default='', help_text='Opportunity number / NOFO number', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('agency_name', models.CharField(blank=True, default='', max_length=255)),
                ('agency_code', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', help_text='Funding category / opportunity category', max_length=255)),
                ('funding_instrument', models.CharField(choices=[('grant', 'Grant'), ('cooperative_agreement', 'Cooperative Agreement'), ('procurement_contract', 'Procurement Contract'), ('other', 'Other')], default='grant', max_length=30)),
                ('cfda_numbers', models.JSONField(blank=True, default=list, help_text='List of CFDA/Assistance Listing numbers')),
                ('award_floor', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum award amount', max_digits=15, null=True)),
                ('award_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum award amount', max_digits=15, null=True)),
                ('expected_awards', models.IntegerField(blank=True, help_text='Expected number of awards', null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, help_text='Total estimated funding', max_digits=15, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('opportunity_status', models.CharField(choices=[('posted', 'Posted'), ('closed', 'Closed'), ('archived', 'Archived'), ('forecasted', 'Forecasted')], default='posted', max_length=15)),
                ('applicant_types', models.JSONField(blank=True, default=list, help_text='List of eligible applicant types')),
                ('eligible_applicants', models.TextField(blank=True, default='', help_text='Additional eligibility text')),
                ('grants_gov_url', models.URLField(blank=True, default='', help_text='Link to the opportunity on Grants.gov', max_length=500)),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='When this record was last synced from Grants.gov')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full API response for this opportunity')),
                ('funding_source', models.ForeignKey(blank=True, help_text='Linked FundingSource when a GrantProgram is created from this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federal_opportunities', to='grants.fundingsource')),
            ],
            options={
                'verbose_name': 'Federal Opportunity',
                'verbose_name_plural': 'Federal Opportunities',
                'ordering': ['-post_date', '-close_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackedOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('preparing', 'Preparing Application'), ('applied', 'Applied'), ('awarded', 'Awarded'), ('declined', 'Declined')], default='watching', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federal_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_records', to='grants.federalopportunity')),
                ('grant_program', models.ForeignKey(blank=True, help_text='Internal Grant Program linked to this federal opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_federal_opportunities', to='grants.grantprogram')),
                ('tracked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracked Opportunity',
                'verbose_name_plural': 'Tracked Opportunities',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', help_text='Email for external collaborators not yet in Beacon', max_length=254)),
                ('name', models.CharField(blank=True, default='', help_text='Name for external collaborators', max_length=255)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('observer', 'Observer')], default='contributor', max_length=15)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='federal_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Internal Beacon user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='federal_collaborations', to=settings.AUTH_USER_MODEL)),
                ('tracked_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='grants.trackedopportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Collaborator',
                'verbose_name_plural': 'Opportunity Collaborators',
                'ordering': ['role', '-invited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='federalopportunity',
            index=models.Index(fields=['opportunity_status', 'close_date'], name='idx_fedopp_status_close'),
        ),
        migrations.AddIndex(
            model_name='federalopportunity',
            index=models.Index(fields=['agency_code'], name='idx_fedopp_agency'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedopportunity',
            unique_together={('federal_opportunity', 'tracked_by')},
        ),
    ]
