# Generated by Django 6.0.2 on 2026-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_federalopportunity_trackedopportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federalopportunity',
            name='opportunity_id',
            field=models.CharField(help_text='Unique identifier from Grants.gov', max_length=64, unique=True),
        ),
    ]
