# Generated by Django 6.0.2 on 2026-02-21 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_change_opportunity_id_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_level', models.CharField(choices=[('watching', 'Watching'), ('interested', 'Interested'), ('planning_to_apply', 'Planning to Apply')], default='watching', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='grants.grantprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Program',
                'verbose_name_plural': 'Saved Programs',
                'ordering': ['-created_at'],
                'unique_together': {('grant_program', 'user')},
            },
        ),
    ]
