# Generated by Django 6.0.2 on 2026-02-23 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_update_grants_gov_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='List of focus area keys from FocusArea choices')),
                ('eligible_org_types', models.JSONField(blank=True, default=list, help_text='List of organization type keys the user is interested in')),
                ('funding_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum funding amount of interest', max_digits=15, null=True)),
                ('funding_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum funding amount of interest', max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Describe your priorities, mission, or what you are looking for in your own words')),
                ('is_active', models.BooleanField(default=True, help_text='Whether AI matching is enabled for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Preference',
                'verbose_name_plural': 'Grant Preferences',
            },
        ),
        migrations.CreateModel(
            name='OpportunityMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('federal', 'Federal'), ('state', 'State')], max_length=10)),
                ('relevance_score', models.IntegerField(help_text='AI relevance score from 0 to 100')),
                ('explanation', models.TextField(blank=True, default='', help_text='AI-generated explanation of why this is a match')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federal_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.federalopportunity')),
                ('grant_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.grantprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Match',
                'verbose_name_plural': 'Opportunity Matches',
                'ordering': ['-relevance_score', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('federal_opportunity__isnull', False)), fields=('user', 'federal_opportunity'), name='unique_user_federal_match'), models.UniqueConstraint(condition=models.Q(('grant_program__isnull', False)), fields=('user', 'grant_program'), name='unique_user_state_match')],
            },
        ),
    ]
