# Generated by Django 6.0.2 on 2026-02-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_add_grant_preference_and_opportunity_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymatch',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', help_text='User feedback on this recommendation', max_length=10),
        ),
        migrations.AddField(
            model_name='opportunitymatch',
            name='feedback_reason',
            field=models.CharField(blank=True, choices=[('wrong_focus', 'Wrong focus area'), ('budget_too_large', 'Budget too large'), ('budget_too_small', 'Budget too small'), ('already_aware', 'Already aware of this'), ('not_eligible', 'Not eligible'), ('not_relevant', 'Not relevant to our mission'), ('other', 'Other')], default='', help_text='Reason for negative feedback', max_length=20),
        ),
    ]
