# Generated by Django 6.0.2 on 2026-02-26 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_opportunitymatch_feedback_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantprogram',
            name='application_deadline',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='grantprogram',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='grantprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('accepting_applications', 'Accepting Applications'), ('under_review', 'Under Review'), ('awards_pending', 'Awards Pending'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=25),
        ),
        migrations.AddIndex(
            model_name='opportunitymatch',
            index=models.Index(fields=['user', 'status'], name='idx_oppmatch_user_status'),
        ),
    ]
