# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('progress', 'Progress'), ('fiscal', 'Fiscal'), ('programmatic', 'Programmatic'), ('final_progress', 'Final Progress'), ('final_fiscal', 'Final Fiscal'), ('sf425', 'SF-425 Federal Financial Report'), ('custom', 'Custom')], max_length=20)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Stores the actual report data.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True, default='')),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='awards.award')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reports/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reporting.report')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_report_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Document',
                'verbose_name_plural': 'Report Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('progress', 'Progress'), ('fiscal', 'Fiscal'), ('programmatic', 'Programmatic'), ('final_progress', 'Final Progress'), ('final_fiscal', 'Final Fiscal'), ('sf425', 'SF-425 Federal Financial Report'), ('custom', 'Custom')], max_length=20)),
                ('sections', models.JSONField(blank=True, default=dict, help_text='Defines the report structure and fields.')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('one_time', 'One Time'), ('as_needed', 'As Needed')], default='quarterly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, help_text='Leave blank for statewide templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='core.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reporting.reporttemplate'),
        ),
        migrations.CreateModel(
            name='SF425Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_period_start', models.DateField()),
                ('reporting_period_end', models.DateField()),
                ('federal_cash_receipts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('federal_expenditures', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('federal_unliquidated_obligations', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('recipient_share_expenditures', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_federal_funds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Stores all SF-425 fields.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sf425_reports', to=settings.AUTH_USER_MODEL)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf425_reports', to='awards.award')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_sf425_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SF-425 Report',
                'verbose_name_plural': 'SF-425 Reports',
                'ordering': ['-reporting_period_end'],
            },
        ),
    ]
