# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseoutChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, default='')),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Closeout Checklist Item',
                'verbose_name_plural': 'Closeout Checklist Items',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='CloseoutDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('final_progress_report', 'Final Progress Report'), ('final_fiscal_report', 'Final Fiscal Report'), ('audit_report', 'Audit Report'), ('inventory_report', 'Inventory Report'), ('refund_documentation', 'Refund Documentation'), ('other', 'Other')], default='other', max_length=25)),
                ('file', models.FileField(upload_to='closeout/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Closeout Document',
                'verbose_name_plural': 'Closeout Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fund Return',
                'verbose_name_plural': 'Fund Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Closeout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed'), ('reopened', 'Reopened')], default='not_started', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closeout', to='awards.award')),
            ],
            options={
                'verbose_name': 'Closeout',
                'verbose_name_plural': 'Closeouts',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
