# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closeout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='closeout',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_closeouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='closeout',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_closeouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='closeoutchecklist',
            name='closeout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='closeout.closeout'),
        ),
        migrations.AddField(
            model_name='closeoutchecklist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='closeoutdocument',
            name='closeout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='closeout.closeout'),
        ),
        migrations.AddField(
            model_name='closeoutdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_closeout_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundreturn',
            name='closeout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_returns', to='closeout.closeout'),
        ),
        migrations.AddField(
            model_name='fundreturn',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fund_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
