# Generated by Django 5.2.15 on 2026-07-14 17:52

import keel.security.scanning
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0005_auditlog_user_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingstep',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Uploaded or drawn signature image (PNG).', null=True, upload_to='signatures/captured/', validators=[keel.security.scanning.FileSecurityValidator()], verbose_name='signature image'),
        ),
        migrations.AlterField(
            model_name='usersignature',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to='signatures/saved/', validators=[keel.security.scanning.FileSecurityValidator()], verbose_name='signature image'),
        ),
    ]
