# Generated by Django 6.0.2 on 2026-02-17 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField()),
                ('special_conditions', models.TextField(blank=True)),
                ('requires_match', models.BooleanField(default=False)),
                ('match_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.IntegerField()),
                ('amendment_type', models.CharField(choices=[('budget_modification', 'Budget Modification'), ('time_extension', 'Time Extension'), ('scope_change', 'Scope Change'), ('personnel_change', 'Personnel Change'), ('other', 'Other')], max_length=25)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='draft', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Award Amendment',
                'verbose_name_plural': 'Award Amendments',
                'ordering': ['award', 'amendment_number'],
            },
        ),
        migrations.CreateModel(
            name='AwardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='awards/docs/')),
                ('document_type', models.CharField(choices=[('agreement', 'Agreement'), ('amendment', 'Amendment'), ('correspondence', 'Correspondence'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Award Document',
                'verbose_name_plural': 'Award Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
