# Generated by Django 6.0.2 on 2026-02-17 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('awards', '0001_initial'),
        ('core', '0001_initial'),
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='core.agency'),
        ),
        migrations.AddField(
            model_name='award',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='applications.application'),
        ),
        migrations.AddField(
            model_name='award',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_awards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='award',
            name='grant_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='grants.grantprogram'),
        ),
        migrations.AddField(
            model_name='award',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='core.organization'),
        ),
        migrations.AddField(
            model_name='award',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awardamendment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awardamendment',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='awards.award'),
        ),
        migrations.AddField(
            model_name='awardamendment',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_amendments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awarddocument',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='awards.award'),
        ),
        migrations.AddField(
            model_name='awarddocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_award_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
