# Generated by Django 6.0.2 on 2026-02-18 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_subrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(choices=[('output', 'Output'), ('outcome', 'Outcome'), ('efficiency', 'Efficiency')], default='output', max_length=15)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('unit_of_measure', models.CharField(help_text='e.g. people served, jobs created', max_length=100)),
                ('reporting_period', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='awards.award')),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['award', 'name'],
            },
        ),
    ]
