# Generated by Django 6.0.2 on 2026-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_add_signaturerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('executed', 'Executed'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
    ]
